CREATE FUNCTION fnRemoveZeros(@TEXTO AS VARCHAR(50), @DIRECAO BIT)
RETURNS VARCHAR(50)) AS

BEGIN
	DECLARE @RETORNO VARCHAR(50)
	IF @DIRECAO = 0  --REMOVE 0 A ESQUERDA
		SET @RETORNO = SUBSTRING(@TEXTO,PATINDEX('%[A-Z,1-9]%',@TEXTO),LEN(@TEXTO)))

	ELSE --REMOVE 0 A DIREIRA
		SET @RETORNO = REVERSE(SUBSTRING(REVERSE(@TEXTO),PATINDEX('%[A-Z,1-9]%',REVERSE(@TEXTO)),LEN(@TEXTO)))
		RETURN (@RETORNO)
	END
