-- ESTE SCRIPT REALIZA A CONCATENAÇÃO DA LISTAGEM DE RESULTADOS DE UMA CONSULTA E RETORNA EM UMA ÚNICA STRING SEPARADOS POR UM DELIMITADOR
DECLARE @DELIMITADOR CHAR(1) = ';'
SELECT TOP 1 
ID, 
NOME, 
(SELECT  FONE + ';' AS [text()] FROM FONES WHERE Devedor_ID = D.devedor_ID FOR XML PATH ('')) AS FONES
FROM CADASTRO
